# example values

indexing-settings:
  sites:
    - url: https://www.svetlovka.ru
      name: Светловка
    - url: https://et-cetera.ru
      name: МОСКОВСКИЙ ТЕАТР «ET CETERA»

server:
  port: 8080

spring:
  datasource:
    username: root
    password: TestTest
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
